/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package przychodnia;

import java.awt.HeadlessException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.Stage;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krystian Tracz
 */
public class dodawanie_prac extends javax.swing.JFrame {
private Connection conn;
 private Statement prepStmt;
 private ResultSet rs;
    /**
     * Creates new form dodawanie_prac
     */
    public void dodawanie_prac() {
        initComponents();
      connect_baza connb = new connect_baza();
      connb.connect();
      SelectPracownicy();
    }
   
       public void SelectPracownicy(){

          connect_baza conbaza = new connect_baza();
        ArrayList<Pracownicy> listpr = conbaza.connect();
        DefaultTableModel model = (DefaultTableModel) tablework.getModel();
       Object[] row = new Object[6];
       for(int i=0; i<listpr.size();i++){
        row[0]= listpr.get(i).getid_Lekarza();
        row[1]= listpr.get(i).getName();
        row[2]= listpr.get(i).getSurname();   
        row[3]= listpr.get(i).getFunction();      
        row[4]= listpr.get(i).getE_mail();  
        row[5]= listpr.get(i).getHaslo();
        model.addRow(row);

       }
        }
          
    
public static void main(String args[]) throws SQLException {
   // connect_baza conb = new connect_baza();
//conb.connect();
     dodawanie_prac dprac = new dodawanie_prac();
     dprac.dodawanie_prac();
     dprac.setVisible(true);
dprac.setTitle("Dodanie pracownika");
            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablework = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        id_lekarza = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        imie = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        e_mail = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        nazwisko = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        haslo = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        specjalnosc = new javax.swing.JTextPane();
        zapisz = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Wyczyść = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tablework.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id_lekarza", "Imie", "Nazwisko", "Specjalność", "E_mail", "Hasło"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablework.setAutoscrolls(false);
        tablework.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tableworkAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tablework);

        jScrollPane2.setViewportView(id_lekarza);

        jScrollPane3.setViewportView(imie);

        jScrollPane4.setViewportView(e_mail);

        jScrollPane5.setViewportView(nazwisko);

        jScrollPane6.setViewportView(haslo);

        jScrollPane7.setViewportView(specjalnosc);

        zapisz.setText("Wstaw");
        zapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapiszActionPerformed(evt);
            }
        });

        jLabel1.setText("Imie");

        jLabel2.setText("Nazwisko");

        jLabel3.setText("Id_lekarza");

        jLabel4.setText("Specjalność");

        jLabel5.setText("E_mail");

        jLabel6.setText("Hasło");

        Wyczyść.setText("Modifikuj");
        Wyczyść.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WyczyśćActionPerformed(evt);
            }
        });

        jButton1.setText("Usuń");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane7)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 44, Short.MAX_VALUE)
                        .addComponent(zapisz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Wyczyść)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zapisz)
                            .addComponent(Wyczyść)
                            .addComponent(jButton1)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WyczyśćActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WyczyśćActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WyczyśćActionPerformed

    private void zapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapiszActionPerformed
try {
    
         CallableStatement call = conn.prepareCall("INSERT INTO lekarze(id_lekarza, imie, nazwisko, specjalnosc, email, haslo) VALUES (?,?,?,?,?,?)");

            call.setString(1,id_lekarza.getText());
            call.setString(2,imie.getText());
            call.setString(3,nazwisko.getText());
            call.setString(4,specjalnosc.getText());
            call.setString(5,e_mail.getText());
            call.setString(6,haslo.getText());
                   DefaultTableModel model = (DefaultTableModel) tablework .getModel();
                   model.setRowCount(0);
                   SelectPracownicy();
                   call.execute();
            //JOptionPane.showMessageDialog(null,"");

        }
        catch(SQLException | HeadlessException ex){

            JOptionPane.showMessageDialog(null, ex);

        }    

        }//GEN-LAST:event_zapiszActionPerformed

    private void tableworkAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tableworkAncestorAdded
try {
    
         CallableStatement call = conn.prepareCall("SELECT (id_lekarza, imie, nazwisko, specjalnosc, email, haslo), (?,?,?,?,?,?)");

             call.setString(1,id_lekarza.getText());
            call.setString(2,imie.getText());
            call.setString(3,nazwisko.getText());
            call.setString(4,specjalnosc.getText());
            call.setString(5,e_mail.getText());
            call.setString(6,haslo.getText());
                   DefaultTableModel model = (DefaultTableModel) tablework .getModel();
                   model.setRowCount(0);
                   SelectPracownicy();
         
                   call.execute();
            //JOptionPane.showMessageDialog(null,"");

        }
        catch(SQLException | HeadlessException ex){

            JOptionPane.showMessageDialog(null, ex);

        }    
        }//GEN-LAST:event_tableworkAncestorAdded

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Wyczyść;
    private javax.swing.JTextPane e_mail;
    private javax.swing.JTextPane haslo;
    private javax.swing.JTextPane id_lekarza;
    private javax.swing.JTextPane imie;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextPane nazwisko;
    private javax.swing.JTextPane specjalnosc;
    public javax.swing.JTable tablework;
    private javax.swing.JButton zapisz;
    // End of variables declaration//GEN-END:variables
}
